nome = input("Digite o nome do cliente: ")
dia_v = input("Digite o dia de vencimento: ")
mes_v = input("Digite o mês de vencimento: ")
fatura = input("Digite o valor da fatura: ")
print("Olá,",nome)
print("A sua fatura com vencimento em",dia_v,"de",mes_v,"no valor de R$",fatura,"está fechada.")